"""joserfc jwk wrapper"""

import uuid
from collections.abc import Callable
from functools import partial
from typing import TypeVar
from joserfc.jwk import ECKey, OctKey
from joserfc_wrapper.Exceptions import (
    GenerateKeysError,
    KeysLoadError,
    KeysNotFoundError,
    KeysNotLoadedError,
    KeysSaveError,
    ObjectTypeError,
    WrapperErrors,
)
from joserfc_wrapper.AbstractKeyStorage import AbstractKeyStorage

T = TypeVar("T")


class WrapJWK:
    """Handles generation, loading, and saving of private, public keys"""

    def __init__(self, storage: AbstractKeyStorage) -> None:
        """
        :param storage: Storage object
        """
        if not isinstance(storage, AbstractKeyStorage):
            raise ObjectTypeError
        self.__storage = storage

        # unicate key id
        self.__kid: str

        # keys (generated or loaded)
        self.__private: dict
        self.__public: dict

        # key for secret a data (JWE)
        self.__secret_key: dict

        # the number of tokens generated by this key
        self.__counter: int

        # True after 'load_keys' or 'generate_keys'
        self.__loaded = False

    def get_kid(self) -> str:
        """
        Return Key ID

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__kid

    def get_public_key(self) -> dict:
        """
        Return public key

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__public

    def get_private_key(self) -> dict:
        """
        Return private key

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__private

    def get_secret_key(self) -> dict:
        """
        Return secret key for encrypted content in claim

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__secret_key

    def get_counter(self) -> int:
        """
        Return token counter

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__counter

    def increase_counter(self) -> None:
        """
        Key Counter plus one (in memory only)

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        self.__counter += 1

    def generate_keys(self) -> None:
        """
        Generate keys

        :raises GenerateKeysError:
        """
        try:
            # generate keys
            self.__kid = uuid.uuid4().hex.lower()
            key = ECKey.generate_key("P-256")

            # Save key for encrypted content
            self.__secret_key = OctKey.generate_key(128).as_dict()

            # Save keys for signing
            self.__private = key.as_dict(private=True)
            self.__public = key.as_dict(private=False)

            # New keys have a zero counter
            self.__counter = 0
            self.__loaded = True

        except Exception as e:
            raise GenerateKeysError from e

    def save_keys(self) -> None:
        """
        Save keys and set them as the last keys

        :raises KeysNotLoadedError:
        :raises KeysSaveError:
        """
        self.__check_loaded()
        self.__call_storage(
            KeysSaveError,
            lambda: self.__storage.save_keys(
                kid=self.__kid, keys=self.__keys()
            ),
        )

    def reserve_key(self, payload: int = 0) -> None:
        """
        Load the last keys and atomically reserve one signature

        Increases the counter of the last keys in the storage. When the
        counter reached the payload, new keys are generated and saved as
        the last keys. Concurrent processes rotate the keys only once and
        a key never signs more than 'payload' tokens (with a storage with
        atomic 'increase_counter' and 'replace_last_keys').

        :param payload: 0 = unlimited, otherwise max tokens signed by a key
        :raises KeysLoadError:
        :raises KeysSaveError: the storage failed or the keys were rotated
            by other processes too many times in a row
        """
        self.load_keys()
        # each attempt fails only when other processes rotated the keys
        # and used up the whole payload of the new keys in the meantime
        for _ in range(100):
            counter = self.__call_storage(
                KeysSaveError,
                partial(self.__storage.increase_counter, self.__kid, payload),
            )
            if counter is not None:
                self.__counter = counter
                return
            last_kid = self.__kid
            self.generate_keys()
            kid = self.__call_storage(
                KeysSaveError,
                partial(
                    self.__storage.replace_last_keys,
                    last_kid=last_kid,
                    kid=self.__kid,
                    keys=self.__keys(),
                ),
            )
            if kid != self.__kid:
                # another process already rotated the keys
                self.load_keys(kid)
        raise KeysSaveError(
            "Unable to reserve a signature, too many rotations."
        )

    def __keys(self) -> dict:
        """Keys and counter in the storage format"""
        # no 'data' keys here, HC Vault add this key automatically
        return {
            "keys": {
                "private": self.__private,
                "public": self.__public,
                "secret": self.__secret_key,
            },
            "counter": self.__counter,
        }

    def load_keys(self, kid: str = "") -> None:
        """
        Load keys and counter from a storage

        :param kid: Unique key ID, default the last keys
        :raises KeysNotFoundError: the keys do not exist in the storage
        :raises KeysLoadError: storage error or invalid keys
        """
        try:
            loaded_kid, result = self.__storage.load_keys(kid=kid)
        except WrapperErrors:
            raise
        except self.__storage.not_found_errors as e:
            raise KeysNotFoundError(f"{type(e).__name__}: {e}") from e
        except Exception as e:
            raise KeysLoadError(f"{type(e).__name__}: {e}") from e

        def load() -> tuple[str, dict, dict, dict, int]:
            data = result["data"]
            return (
                loaded_kid,
                data["keys"]["public"],
                data["keys"]["private"],
                data["keys"]["secret"],
                data["counter"],
            )

        # assign only complete keys, a failed load keeps the loaded keys
        (
            self.__kid,
            self.__public,
            self.__private,
            self.__secret_key,
            self.__counter,
        ) = self.__call_storage(KeysLoadError, load)
        self.__loaded = True

    def __check_loaded(self) -> None:
        if not self.__loaded:
            raise KeysNotLoadedError

    @staticmethod
    def __call_storage(error: type[WrapperErrors], call: Callable[[], T]) -> T:
        """
        Call the storage, wrap its errors (file, Vault, custom storage)

        The original exception is available as '__cause__'.
        """
        try:
            return call()
        except WrapperErrors:
            raise
        except Exception as e:
            raise error(f"{type(e).__name__}: {e}") from e
