"""joserfc jwk wrapper"""

import time
import uuid
from collections.abc import Callable
from functools import partial
from typing import TypeVar
from joserfc.jwk import ECKey, OctKey
from joserfc_wrapper.exceptions import (
    ConfigurationError,
    GenerateKeysError,
    KeysLoadError,
    KeysNotFoundError,
    KeysNotLoadedError,
    KeysSaveError,
    ObjectTypeError,
    WrapperErrors,
)
from joserfc_wrapper.abstract_key_storage import AbstractKeyStorage

T = TypeVar("T")

# metadata fields of a key record (unix timestamps or None)
METADATA = ("created", "retired", "revoked")


class WrapJWK:
    """
    Handles generation, loading, and saving of private, public keys

    The methods used by WrapJWT and WrapJWE ('reserve_signing_key',
    'load_verification_key', 'load_secret_key', 'revoke_jti',
    'is_jti_revoked') and 'jwks', 'list_keys' and 'prune' are safe for
    threads. 'rotate', 'revoke', 'load_keys', 'generate_keys', 'save_keys',
    'reserve_key' and the getters of the loaded keys keep state, use a
    separate WrapJWK for them.
    """

    def __init__(self, storage: AbstractKeyStorage) -> None:
        """
        :param storage: Storage object
        """
        if not isinstance(storage, AbstractKeyStorage):
            raise ObjectTypeError
        self.__storage = storage

        # unicate key id
        self.__kid: str

        # keys (generated or loaded)
        self.__private: dict
        self.__public: dict

        # key for secret a data (JWE)
        self.__secret_key: dict

        # the number of tokens generated by this key
        self.__counter: int

        # metadata: created, retired (stopped to be the last keys), revoked
        self.__metadata: dict[str, int | None] = {}

        # True after 'load_keys' or 'generate_keys'
        self.__loaded = False

    def get_kid(self) -> str:
        """
        Return Key ID

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__kid

    def get_public_key(self) -> dict:
        """
        Return public key

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__public

    def get_private_key(self) -> dict:
        """
        Return private key

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__private

    def get_secret_key(self) -> dict:
        """
        Return secret key for encrypted content in claim

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__secret_key

    def get_counter(self) -> int:
        """
        Return token counter

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__counter

    def get_created(self) -> int | None:
        """
        Return the creation time of the keys (unix timestamp), None for
        keys created by versions older than 0.5.0

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__metadata.get("created")

    def get_retired(self) -> int | None:
        """
        Return the time when the keys stopped to be the last keys (unix
        timestamp), None for the last keys or unknown

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__metadata.get("retired")

    def get_revoked(self) -> int | None:
        """
        Return the time of revocation (unix timestamp), None when the keys
        are not revoked

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        return self.__metadata.get("revoked")

    def is_revoked(self) -> bool:
        """
        Return True when the keys are revoked, tokens signed by them are
        invalid

        :raises KeysNotLoadedError:
        """
        return self.get_revoked() is not None

    def increase_counter(self) -> None:
        """
        Key Counter plus one (in memory only)

        :raises KeysNotLoadedError:
        """
        self.__check_loaded()
        self.__counter += 1

    def generate_keys(self) -> None:
        """
        Generate keys

        :raises GenerateKeysError:
        """
        try:
            # generate keys
            self.__kid = uuid.uuid4().hex.lower()
            key = ECKey.generate_key("P-256")

            # Save key for encrypted content
            self.__secret_key = OctKey.generate_key(128).as_dict()

            # Save keys for signing
            self.__private = key.as_dict(private=True)
            self.__public = key.as_dict(private=False)

            # New keys have a zero counter
            self.__counter = 0
            self.__metadata = {"created": int(time.time())}
            self.__loaded = True

        except Exception as e:
            raise GenerateKeysError from e

    def save_keys(self) -> None:
        """
        Save keys and set them as the last keys

        :raises KeysNotLoadedError:
        :raises KeysSaveError:
        """
        self.__check_loaded()
        self.__call_storage(
            KeysSaveError,
            lambda: self.__storage.save_keys(
                kid=self.__kid, keys=self.__keys()
            ),
        )
        self.__storage.clear_key_cache(self.__kid)

    def reserve_key(
        self, payload: int = 0, max_key_age: int | None = None
    ) -> None:
        """
        Load the last keys and atomically reserve one signature

        Increases the counter of the last keys in the storage. New keys
        are generated and saved as the last keys when the last keys are
        older than 'max_key_age', revoked, or when the counter reached the
        payload. Concurrent processes rotate the keys only once (with a
        storage with atomic 'increase_counter' and 'replace_last_keys').

        :param payload: deprecated, 0 = unlimited, otherwise max tokens
            signed by a key
        :param max_key_age: None = unlimited, otherwise the keys are
            rotated after this number of seconds since their creation
            (keys without the creation time are rotated)
        :raises KeysLoadError:
        :raises KeysSaveError: the storage failed or the keys were rotated
            by other processes too many times in a row
        """
        self.load_keys()
        # each attempt fails only when other processes rotated the keys
        # and the new keys reached a limit in the meantime
        for _ in range(100):
            if self.is_revoked() or self.__too_old(max_key_age):
                self.__rotate()
                continue
            counter = self.__call_storage(
                KeysSaveError,
                partial(self.__storage.increase_counter, self.__kid, payload),
            )
            if counter is not None:
                self.__counter = counter
                return
            self.__rotate()
        raise KeysSaveError(
            "Unable to reserve a signature, too many rotations."
        )

    def reserve_signing_key(
        self, payload: int = 0, max_key_age: int | None = None
    ) -> tuple[str, dict]:
        """
        Reserve one signature like 'reserve_key' and return the signing
        key, used by 'WrapJWT.create'

        The loaded keys of this object do not change, so one WrapJWK can be
        shared by threads.

        :param payload: deprecated, see 'reserve_key'
        :param max_key_age: see 'reserve_key'
        :returns: Key ID and the private key (JWK dict)
        :raises KeysLoadError:
        :raises KeysSaveError:
        """
        worker = WrapJWK(self.__storage)
        worker.reserve_key(payload, max_key_age)
        return worker.get_kid(), worker.get_private_key()

    def load_secret_key(self, kid: str = "") -> tuple[str, dict]:
        """
        Return the secret key for encrypted data (JWE), used by WrapJWE

        The loaded keys of this object do not change.

        :param kid: Key ID, default the last keys
        :returns: Key ID and the secret key (JWK dict)
        :raises KeysNotFoundError: the keys do not exist in the storage
        :raises KeysLoadError: storage error or invalid keys
        """
        loaded_kid, data = self.__load_record(kid)
        secret = self.__call_storage(
            KeysLoadError, lambda: data["keys"]["secret"]
        )
        return loaded_kid, secret

    def rotate(self) -> None:
        """
        Generate new keys and save them as the last keys

        The previous last keys are marked as retired, tokens signed by them
        stay valid until they expire. Without any keys in the storage the
        first keys are created. After a concurrent rotation by another
        process its keys are loaded instead.

        :raises KeysLoadError:
        :raises KeysSaveError:
        """
        try:
            self.load_keys()
        except KeysNotFoundError:
            self.generate_keys()
            self.save_keys()
            return
        self.__rotate()

    def revoke(self, kid: str) -> None:
        """
        Revoke keys, tokens signed by them are invalid ('verify' raises
        TokenKeyRevokedError)

        The keys stay in the storage with the time of revocation. When
        they are the last keys, new keys are generated first, so creating
        tokens continues. The revoked keys are deleted by 'prune' later.

        :param kid: Key ID
        :raises KeysNotFoundError: the keys are not in the storage
        :raises KeysLoadError:
        :raises KeysSaveError:
        """
        self.__load_record(kid)
        last_kid = self.__call_storage(
            KeysLoadError, self.__storage.get_last_kid
        )
        if kid == last_kid:
            self.rotate()
        self.__call_storage(
            KeysSaveError,
            partial(
                self.__storage.update_metadata,
                kid,
                {"revoked": int(time.time())},
            ),
        )
        # verify in this process rejects the tokens immediately
        self.__storage.clear_key_cache(kid)

    def load_verification_key(self, kid: str) -> tuple[dict, int | None]:
        """
        Return the public key and the time of revocation of a key, cached
        by the storage ('key_cache_ttl'), used by 'WrapJWT.verify'

        The loaded keys of this object do not change.

        :param kid: Key ID
        :returns: public key (JWK dict) and revoked (unix timestamp or None)
        :raises KeysNotFoundError: the keys do not exist in the storage
        :raises KeysLoadError: storage error or invalid keys
        """
        return self.__load(partial(self.__storage.load_verification_key, kid))

    def jwks(self) -> dict:
        """
        Return the public keys as a JWK Set (RFC 7517) for other services
        which verify tokens, e.g. from an endpoint /.well-known/jwks.json

        Contains all keys in the storage except revoked keys (the last and
        the retired keys, tokens signed by them are valid until they
        expire), never the private keys or the JWE secret keys. New keys
        are included immediately after a rotation.

        :returns: {"keys": [{"kid", "kty", "crv", "x", "y", "use", "alg"}]}
        :raises KeysLoadError: storage error or the storage does not
            support listing keys (Vault needs the 'list' capability)
        """
        return self.__call_storage(KeysLoadError, self.__storage.load_jwks)

    def list_keys(self) -> list[dict]:
        """
        Return all keys in the storage with their metadata, sorted by the
        creation time (keys without it first), the last keys at the end

        Each item: kid, last (bool), created, retired, revoked, counter.
        The private keys are not returned.

        :raises KeysLoadError: storage error or the storage does not
            support listing keys
        """
        kids = self.__call_storage(KeysLoadError, self.__storage.list_kids)
        last_kid = self.__call_storage(
            KeysLoadError, self.__storage.get_last_kid
        )
        items = []
        for kid in kids:
            _, data = self.__load_record(kid)
            items.append(
                {
                    "kid": kid,
                    "last": kid == last_kid,
                    **{field: data.get(field) for field in METADATA},
                    "counter": data.get("counter"),
                }
            )
        # the last keys are always at the end (keys created in the same second)
        return sorted(
            items, key=lambda item: (item["last"], item["created"] or 0)
        )

    def prune(self, max_token_lifetime: int, leeway: int = 0) -> list[str]:
        """
        Delete keys which cannot sign any valid token anymore

        A key is deleted when it is not the last key and more than
        'max_token_lifetime' (+ leeway) seconds passed since it was retired,
        so all tokens signed by it have expired. Keys without the retirement
        time (created by versions older than 0.5.0) are never deleted. Run
        it from the application or cron, never automatically. Records of
        revoked tokens which expired are deleted too.

        :param max_token_lifetime: the longest lifetime of a token in
            seconds ('max_token_lifetime' of WrapJWT)
        :param leeway: tolerance of clocks in seconds
        :returns: Key IDs of deleted keys
        :raises ConfigurationError: invalid max_token_lifetime or leeway
        :raises KeysLoadError: storage error or the storage does not
            support listing keys
        :raises KeysSaveError: the keys were not deleted
        """
        for name, value, minimum in (
            ("max_token_lifetime", max_token_lifetime, 1),
            ("leeway", leeway, 0),
        ):
            # bool is a subclass of int
            if (
                not isinstance(value, int)
                or isinstance(value, bool)
                or value < minimum
            ):
                raise ConfigurationError(
                    f"'{name}' must be an integer {minimum} or greater."
                )
        now = int(time.time())
        deleted = []
        for item in self.list_keys():
            retired = item["retired"]
            if item["last"] or retired is None:
                continue
            if now > retired + max_token_lifetime + leeway:
                self.__call_storage(
                    KeysSaveError,
                    partial(self.__storage.delete_keys, item["kid"]),
                )
                self.__storage.clear_key_cache(item["kid"])
                deleted.append(item["kid"])
        # records of revoked tokens which expired (storages without TTL)
        if self.supports_token_revocation():
            self.__call_storage(
                KeysSaveError,
                partial(self.__storage.prune_revoked, now - leeway),
            )
        return deleted

    def supports_token_revocation(self) -> bool:
        """Return True when the storage can revoke single tokens (jti)"""
        return self.__storage.supports_token_revocation()

    def revoke_jti(self, jti: str, expires_at: int) -> None:
        """
        Save a revoked token ID until the token expires

        :param jti: token ID
        :param expires_at: 'exp' of the token (unix timestamp)
        :raises KeysSaveError: storage error or not supported
        """
        self.__call_storage(
            KeysSaveError,
            partial(self.__storage.revoke_jti, jti, expires_at),
        )

    def is_jti_revoked(self, jti: str) -> bool:
        """
        Return True when the token ID is revoked

        :param jti: token ID
        :raises KeysLoadError: storage error or not supported
        """
        return self.__call_storage(
            KeysLoadError, partial(self.__storage.is_jti_revoked, jti)
        )

    def __too_old(self, max_key_age: int | None) -> bool:
        """The loaded keys are older than max_key_age (or without age)"""
        if max_key_age is None:
            return False
        created = self.__metadata.get("created")
        return created is None or int(time.time()) - created >= max_key_age

    def __rotate(self) -> None:
        """
        Replace the loaded last keys by new keys, mark them retired

        After a concurrent rotation by another process its keys are loaded.
        """
        last_kid = self.__kid
        self.generate_keys()
        kid = self.__call_storage(
            KeysSaveError,
            partial(
                self.__storage.replace_last_keys,
                last_kid=last_kid,
                kid=self.__kid,
                keys=self.__keys(),
            ),
        )
        if kid != self.__kid:
            # another process already rotated the keys
            self.load_keys(kid)
            return
        self.__call_storage(
            KeysSaveError,
            partial(
                self.__storage.update_metadata,
                last_kid,
                {"retired": self.__metadata["created"]},
            ),
        )

    def __keys(self) -> dict:
        """Keys, counter and metadata in the storage format"""
        # no 'data' keys here, HC Vault add this key automatically
        keys: dict = {
            "keys": {
                "private": self.__private,
                "public": self.__public,
                "secret": self.__secret_key,
            },
            "counter": self.__counter,
        }
        keys.update({k: v for k, v in self.__metadata.items() if v is not None})
        return keys

    def load_keys(self, kid: str = "") -> None:
        """
        Load keys, counter and metadata from a storage

        :param kid: Unique key ID, default the last keys
        :raises KeysNotFoundError: the keys do not exist in the storage
        :raises KeysLoadError: storage error or invalid keys
        """
        loaded_kid, data = self.__load_record(kid)

        def load() -> tuple[str, dict, dict, dict, int, dict]:
            return (
                loaded_kid,
                data["keys"]["public"],
                data["keys"]["private"],
                data["keys"]["secret"],
                data["counter"],
                {field: data.get(field) for field in METADATA},
            )

        # assign only complete keys, a failed load keeps the loaded keys
        (
            self.__kid,
            self.__public,
            self.__private,
            self.__secret_key,
            self.__counter,
            self.__metadata,
        ) = self.__call_storage(KeysLoadError, load)
        self.__loaded = True

    def __load_record(self, kid: str) -> tuple[str, dict]:
        """
        Load a key record (the 'data' part) from the storage

        :raises KeysNotFoundError: the keys do not exist in the storage
        :raises KeysLoadError: storage error
        """
        loaded_kid, result = self.__load(
            partial(self.__storage.load_keys, kid=kid)
        )
        return loaded_kid, result["data"]

    def __load(self, call: Callable[[], T]) -> T:
        """
        Call a loading method of the storage, wrap its errors

        :raises KeysNotFoundError: the keys do not exist in the storage
        :raises KeysLoadError: storage error
        """
        try:
            return call()
        except WrapperErrors:
            raise
        except self.__storage.not_found_errors as e:
            raise KeysNotFoundError(f"{type(e).__name__}: {e}") from e
        except Exception as e:
            raise KeysLoadError(f"{type(e).__name__}: {e}") from e

    def __check_loaded(self) -> None:
        if not self.__loaded:
            raise KeysNotLoadedError

    @staticmethod
    def __call_storage(error: type[WrapperErrors], call: Callable[[], T]) -> T:
        """
        Call the storage, wrap its errors (file, Vault, custom storage)

        The original exception is available as '__cause__'.
        """
        try:
            return call()
        except WrapperErrors:
            raise
        except Exception as e:
            raise error(f"{type(e).__name__}: {e}") from e
